export const ENDPOINTS = {
  tours: '/tours',
  tourById: (id: string) => `/tours/${id}`,
  categories: '/categories',
  categoryTree: '/categories/tree',
  categoryById: (id: string) => `/categories/${id}`,
  guides: '/guides',
  guideById: (id: string) => `/guides/${id}`,
  guideRating: (id: string) => `/guides/${id}/rating`,
  guideTourHistory: (id: string) => `/guides/${id}/history`,
  guideStatistics: '/guides/statistics',
  providers: '/providers',
  providerById: (id: string) => `/providers/${id}`,
  vehicles: '/vehicles',
  vehicleById: (id: string) => `/vehicles/${id}`,
  hotels: '/hotels',
  hotelById: (id: string) => `/hotels/${id}`,
  rooms: '/rooms',
  roomById: (id: string) => `/rooms/${id}`,
  restaurants: '/restaurants',
  restaurantById: (id: string) => `/restaurants/${id}`,
  providerTickets: '/provider-tickets',
  providerTicketById: (id: string) => `/provider-tickets/${id}`,

  wishlistTours: '/wishlist-tours',
  wishlistTourStatus: (tourId: string) => `/wishlist-tours/status/${tourId}`,
  wishlistTourById: (tourId: string) => `/wishlist-tours/${tourId}`,

  tourReviews: '/tour-reviews',
  tourReviewMeById: (id: string) => `/tour-reviews/me/${id}`,
  tourReviewById: (id: string) => `/tour-reviews/${id}`,
  tourReviewPublicList: '/tour-reviews/public/list',
} as const;


